// vg_audio_envelope_composer.dart
// Vanguard Media Engine — Phase 10-C Slice V-C: Added Audio Fade Envelope Composer.
//
// Pure-Dart offline utility. No channel calls, no rendering logic.
//
// Responsibilities:
//   - For each Added Audio sidecar track (music, sfx, voiceover):
//       - If the track already has non-empty volumeKeyframes: preserve unchanged.
//       - If fadeInSeconds or fadeOutSeconds is non-zero: derive a fade-only
//         envelope using output-timeline seconds (same basis as startTime).
//       - Music/sfx tracks may additionally carry ducking keyframes generated by
//         VGAudioDuckingEngine. composeWithDucking() applies the fade as a
//         normalized scale [0,1] over the existing ducking absolute-gain envelope.
//   - Voiceover tracks receive fade keyframes but are never ducked.
//   - Original/null/unknown roles are passed through unchanged.
//   - mixGain is preserved as a separate field and is never baked into keyframes.
//   - All input tracks and lists are treated as immutable.
//
// Design contract:
//   - Keyframe times are output-timeline seconds (same basis as startTime).
//   - Only 'linear' curve is used (matches Phase 8.15A constraint).
//   - Standalone derive(): volume values are absolute gain in [0, track.volume].
//     The fade-in ramp goes from 0.0 at startTime to track.volume at
//     startTime + effectiveFadeIn. The fade-out ramp goes from track.volume at
//     trackEnd - effectiveFadeOut to 0.0 at trackEnd.
//   - composeWithDucking(): the fade is treated as a normalized scale in [0,1]
//     (0 at fade edges, 1 at sustain) applied to the ducking absolute gain.
//     At sustain the scale is 1.0, so duckingGain is preserved unchanged.
//     Result at time t = duckingAbsoluteGain(t) * fadeNormalizedScale(t).
//   - Overlap handling (matches VGAudioExportMuxer.m:923-933):
//       1. Clamp each fade individually to trackDuration.
//       2. If effectiveFadeIn + effectiveFadeOut > trackDuration, scale both
//          proportionally by factor = trackDuration / total.

import '../../vg_audio_sidecar_plan.dart';

/// Phase 10-C Slice V-C: Derives volumeKeyframes for Added Audio fade
/// envelopes and optionally composes them with an existing ducking envelope.
///
/// **Role handling:**
///   - `'music'`, `'sfx'`: fade envelope may be composed with ducking keyframes
///     generated by [VGAudioDuckingEngine] in the same `apply()` call.
///   - `'voiceover'`: fade envelope is derived independently; ducking is
///     never applied to voiceover.
///   - `'original'`, null, unknown: track is returned unchanged.
///
/// **Skip conditions for [derive]:**
///   - Track already has non-empty volumeKeyframes: returned unchanged.
///   - Both fadeInSeconds and fadeOutSeconds are zero: returned unchanged.
final class VGAudioEnvelopeComposer {
  const VGAudioEnvelopeComposer();

  // ── Role helpers ──────────────────────────────────────────────────────────

  static bool _isMusicOrSfx(String? role) => role == 'music' || role == 'sfx';

  static bool _isVoiceover(String? role) => role == 'voiceover';

  // ── Public API ────────────────────────────────────────────────────────────

  /// Derives a standalone fade envelope for a single [track] with no ducking.
  ///
  /// Volume values are absolute gain in `[0, track.volume]`.
  /// Returns the track unchanged when:
  ///   - Role is not music/sfx/voiceover.
  ///   - Track already has non-empty volumeKeyframes.
  ///   - Both fades are zero.
  VGAudioSidecarTrack derive(VGAudioSidecarTrack track) {
    if (!_isMusicOrSfx(track.role) && !_isVoiceover(track.role)) return track;
    if (track.volumeKeyframes != null && track.volumeKeyframes!.isNotEmpty) {
      return track; // pre-authored keyframes: preserve unchanged
    }
    if (track.fadeInSeconds <= 0.0 && track.fadeOutSeconds <= 0.0) {
      return track; // no fade requested
    }

    final kfs = _buildFadeEnvelope(track);
    if (kfs == null || kfs.isEmpty) return track;

    return _copyWithKeyframes(track, kfs);
  }

  /// Composes fade with an existing ducking envelope for a music/sfx track.
  ///
  /// [duckingKeyframes] are the absolute-gain volumeKeyframes already set on
  /// [track] by [VGAudioDuckingEngine] in the same `apply()` call.
  ///
  /// The fade is applied as a **normalized scale** in `[0, 1]`:
  ///   - 0 at the fade-in start and fade-out end.
  ///   - 1 throughout the sustain region.
  ///
  /// The result at each breakpoint time `t` is:
  ///   `duckingAbsoluteGain(t) × fadeNormalizedScale(t)`
  ///
  /// This ensures that at sustain (scale = 1.0) the ducking gain is preserved
  /// exactly — a non-unity `track.volume` is never squared.
  ///
  /// Returns the track unchanged when both fades are zero.
  VGAudioSidecarTrack composeWithDucking(
    VGAudioSidecarTrack track,
    List<VGAudioVolumeKeyframe> duckingKeyframes,
  ) {
    if (track.fadeInSeconds <= 0.0 && track.fadeOutSeconds <= 0.0) {
      return track;
    }

    // Build the normalized fade scale curve [0, 1].
    final fadeScale = _buildNormalizedFadeScale(track);
    if (fadeScale == null || fadeScale.isEmpty) return track;

    // Compose: result(t) = duckingAbsoluteGain(t) * fadeNormalizedScale(t).
    final composed = _applyFadeScale(duckingKeyframes, fadeScale);
    final deduped = _dedup(composed);
    return _copyWithKeyframes(track, deduped);
  }

  // ── Effective fade durations (shared overlap logic) ───────────────────────

  /// Computes effective fade-in and fade-out durations matching native behavior
  /// (VGAudioExportMuxer.m:923-933):
  ///   1. Clamp each requested fade individually to [0, trackDuration].
  ///   2. If their sum still exceeds trackDuration, scale both proportionally.
  static ({double fadeIn, double fadeOut}) _effectiveFades(
    double requestedFadeIn,
    double requestedFadeOut,
    double trackDuration,
  ) {
    // Step 1: per-fade clamp.
    var fi = requestedFadeIn.clamp(0.0, trackDuration);
    var fo = requestedFadeOut.clamp(0.0, trackDuration);

    // Step 2: proportional scale if their sum still exceeds duration.
    final total = fi + fo;
    if (total > trackDuration && total > 1e-9) {
      final scale = trackDuration / total;
      fi = fi * scale;
      fo = fo * scale;
    }

    return (fadeIn: fi, fadeOut: fo);
  }

  // ── Standalone absolute-gain fade envelope ────────────────────────────────

  /// Builds a fade-only keyframe envelope with absolute gain in
  /// `[0, track.volume]`.
  ///
  /// Returns null when both fades are zero or track duration is non-positive.
  List<VGAudioVolumeKeyframe>? _buildFadeEnvelope(VGAudioSidecarTrack track) {
    final trackStart = track.startTime;
    final trackEnd = track.startTime + track.duration;
    final trackDuration = track.duration;
    final normalVolume = track.volume;

    if (trackEnd <= trackStart) return null;

    final hasFadeIn = track.fadeInSeconds > 0.0;
    final hasFadeOut = track.fadeOutSeconds > 0.0;
    if (!hasFadeIn && !hasFadeOut) return null;

    final fades = _effectiveFades(
      track.fadeInSeconds,
      track.fadeOutSeconds,
      trackDuration,
    );

    final fadeInEnd = (trackStart + fades.fadeIn).clamp(trackStart, trackEnd);
    final fadeOutStart = (trackEnd - fades.fadeOut).clamp(trackStart, trackEnd);

    final kfs = <VGAudioVolumeKeyframe>[];

    // ── Fade-in only ────────────────────────────────────────────────────────
    if (hasFadeIn && !hasFadeOut) {
      kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: 0.0));
      if (fadeInEnd > trackStart + 1e-6) {
        kfs.add(VGAudioVolumeKeyframe(time: fadeInEnd, volume: normalVolume));
      }
      if (trackEnd - fadeInEnd > 1e-6) {
        kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: normalVolume));
      }
      return kfs;
    }

    // ── Fade-out only ───────────────────────────────────────────────────────
    if (hasFadeOut && !hasFadeIn) {
      kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: normalVolume));
      if (fadeOutStart - trackStart > 1e-6) {
        kfs.add(
          VGAudioVolumeKeyframe(time: fadeOutStart, volume: normalVolume),
        );
      }
      kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: 0.0));
      return kfs;
    }

    // ── Both fade-in and fade-out ───────────────────────────────────────────
    // After clamping + proportional scaling, fadeInEnd <= fadeOutStart always.
    // Emit: 0 → normalVolume → [normalVolume] → 0.
    kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: 0.0));
    kfs.add(VGAudioVolumeKeyframe(time: fadeInEnd, volume: normalVolume));
    if (fadeOutStart - fadeInEnd > 1e-6) {
      kfs.add(VGAudioVolumeKeyframe(time: fadeOutStart, volume: normalVolume));
    }
    kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: 0.0));

    return kfs;
  }

  // ── Normalized fade scale [0, 1] for composition ──────────────────────────

  /// Builds a normalized fade scale curve with values in `[0, 1]`.
  ///
  /// At fade-in start and fade-out end the scale is 0.0.
  /// Throughout the sustain region the scale is 1.0.
  /// Returns null when both fades are zero or track duration is non-positive.
  List<VGAudioVolumeKeyframe>? _buildNormalizedFadeScale(
    VGAudioSidecarTrack track,
  ) {
    final trackStart = track.startTime;
    final trackEnd = track.startTime + track.duration;
    final trackDuration = track.duration;

    if (trackEnd <= trackStart) return null;

    final hasFadeIn = track.fadeInSeconds > 0.0;
    final hasFadeOut = track.fadeOutSeconds > 0.0;
    if (!hasFadeIn && !hasFadeOut) return null;

    final fades = _effectiveFades(
      track.fadeInSeconds,
      track.fadeOutSeconds,
      trackDuration,
    );

    final fadeInEnd = (trackStart + fades.fadeIn).clamp(trackStart, trackEnd);
    final fadeOutStart = (trackEnd - fades.fadeOut).clamp(trackStart, trackEnd);

    final kfs = <VGAudioVolumeKeyframe>[];

    // ── Fade-in only ────────────────────────────────────────────────────────
    if (hasFadeIn && !hasFadeOut) {
      kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: 0.0));
      if (fadeInEnd > trackStart + 1e-6) {
        kfs.add(VGAudioVolumeKeyframe(time: fadeInEnd, volume: 1.0));
      }
      if (trackEnd - fadeInEnd > 1e-6) {
        kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: 1.0));
      }
      return kfs;
    }

    // ── Fade-out only ───────────────────────────────────────────────────────
    if (hasFadeOut && !hasFadeIn) {
      kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: 1.0));
      if (fadeOutStart - trackStart > 1e-6) {
        kfs.add(VGAudioVolumeKeyframe(time: fadeOutStart, volume: 1.0));
      }
      kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: 0.0));
      return kfs;
    }

    // ── Both ────────────────────────────────────────────────────────────────
    kfs.add(VGAudioVolumeKeyframe(time: trackStart, volume: 0.0));
    kfs.add(VGAudioVolumeKeyframe(time: fadeInEnd, volume: 1.0));
    if (fadeOutStart - fadeInEnd > 1e-6) {
      kfs.add(VGAudioVolumeKeyframe(time: fadeOutStart, volume: 1.0));
    }
    kfs.add(VGAudioVolumeKeyframe(time: trackEnd, volume: 0.0));

    return kfs;
  }

  // ── Envelope composition ──────────────────────────────────────────────────

  /// Applies a normalized fade scale to an absolute-gain ducking envelope.
  ///
  /// At each distinct breakpoint `t` from either envelope:
  ///   `result(t) = duckingAbsoluteGain(t) × fadeNormalizedScale(t)`
  ///
  /// Because the fade scale is 1.0 at sustain, the ducking gain passes through
  /// unchanged in regions where no fade is active.
  List<VGAudioVolumeKeyframe> _applyFadeScale(
    List<VGAudioVolumeKeyframe> ducking,
    List<VGAudioVolumeKeyframe> fadeScale,
  ) {
    // Collect all distinct breakpoint times from both envelopes.
    final times = <double>{};
    for (final kf in ducking) {
      times.add(kf.time);
    }
    for (final kf in fadeScale) {
      times.add(kf.time);
    }
    final sortedTimes = times.toList()..sort();

    final result = <VGAudioVolumeKeyframe>[];
    for (final t in sortedTimes) {
      final duckGain = _interpolate(ducking, t);
      final scale = _interpolateScale(fadeScale, t);
      result.add(
        VGAudioVolumeKeyframe(
          time: t,
          volume: (duckGain * scale).clamp(0.0, 1.0),
        ),
      );
    }
    return result;
  }

  // ── Interpolation helpers ─────────────────────────────────────────────────

  /// Linearly interpolates an absolute-gain keyframe list at time [t].
  ///
  /// When [t] is before the first keyframe, returns the first volume.
  /// When [t] is after the last keyframe, returns the last volume.
  static double _interpolate(List<VGAudioVolumeKeyframe> kfs, double t) {
    if (kfs.isEmpty) return 1.0;
    if (t <= kfs.first.time) return kfs.first.volume;
    if (t >= kfs.last.time) return kfs.last.volume;

    for (var i = 0; i < kfs.length - 1; i++) {
      final a = kfs[i];
      final b = kfs[i + 1];
      if (t >= a.time && t <= b.time) {
        if ((b.time - a.time) < 1e-9) return a.volume;
        final frac = (t - a.time) / (b.time - a.time);
        return (a.volume + frac * (b.volume - a.volume)).clamp(0.0, 1.0);
      }
    }
    return kfs.last.volume;
  }

  /// Linearly interpolates a normalized scale keyframe list at time [t].
  ///
  /// Default outside the envelope is 1.0 (no scaling applied). This ensures
  /// that ducking gain is unaffected in regions outside the fade window.
  static double _interpolateScale(List<VGAudioVolumeKeyframe> kfs, double t) {
    if (kfs.isEmpty) return 1.0;
    if (t <= kfs.first.time) return kfs.first.volume;
    if (t >= kfs.last.time) return kfs.last.volume;

    for (var i = 0; i < kfs.length - 1; i++) {
      final a = kfs[i];
      final b = kfs[i + 1];
      if (t >= a.time && t <= b.time) {
        if ((b.time - a.time) < 1e-9) return a.volume;
        final frac = (t - a.time) / (b.time - a.time);
        return (a.volume + frac * (b.volume - a.volume)).clamp(0.0, 1.0);
      }
    }
    return kfs.last.volume;
  }

  // ── Helpers ───────────────────────────────────────────────────────────────

  static VGAudioSidecarTrack _copyWithKeyframes(
    VGAudioSidecarTrack track,
    List<VGAudioVolumeKeyframe> keyframes,
  ) => VGAudioSidecarTrack(
    trackId: track.trackId,
    url: track.url,
    startTime: track.startTime,
    duration: track.duration,
    volume: track.volume,
    role: track.role,
    fadeInSeconds: track.fadeInSeconds,
    fadeOutSeconds: track.fadeOutSeconds,
    timeRemapAudioPolicy: track.timeRemapAudioPolicy,
    sourceTrimStartSeconds: track.sourceTrimStartSeconds,
    volumeKeyframes: keyframes,
    mixGain: track.mixGain,
  );

  /// Removes consecutive keyframes at the same time and volume.
  static List<VGAudioVolumeKeyframe> _dedup(List<VGAudioVolumeKeyframe> kfs) {
    if (kfs.length <= 1) return kfs;
    final out = <VGAudioVolumeKeyframe>[kfs.first];
    for (var i = 1; i < kfs.length; i++) {
      final prev = out.last;
      final curr = kfs[i];
      if ((curr.time - prev.time).abs() < 1e-9 &&
          (curr.volume - prev.volume).abs() < 1e-9) {
        continue;
      }
      out.add(curr);
    }
    return out;
  }
}
