// vanguard_editor_controller_playground.dart
// Vanguard Media Engine — Phase 7 Stage 7.7: Editor Controller Playground
//
// ═══════════════════════════════════════════════════════════════════════════════
// STAGE 7.7 — EDITOR CONTROLLER PLAYGROUND
// ═══════════════════════════════════════════════════════════════════════════════
//
// Proves that VGEditorController and VGEditorDraft correctly coordinate the
// Phase 7.6-proven dev_ MethodChannel routes through the new formal API.
//
// This playground is additive and does NOT modify the existing raw
// vanguard_timeline_playback_playground.dart (Stage 7.6 regression baseline).
//
// PROOF CRITERIA:
//   1. initialize() produces a valid textureId and 10s draft duration.
//   2. play() / pause() toggle playback via VGEditorController state.
//   3. Seek slider updates currentPTS via handleNativeCallback delegation.
//   4. Trim A → 3s: updateDraft() rebuilds to ~8s timeline.
//   5. Trim B → 3s: updateDraft() rebuilds to ~6s timeline.
//   6. Reset: updateDraft() rebuilds back to 10s baseline.
//   7. Export after trim produces a shorter MP4 with correct duration.
//
// METHOCHANNEL OWNERSHIP (Opus M1):
//   This widget owns _channel.setMethodCallHandler.
//   It delegates ALL callbacks to controller.handleNativeCallback().
//   VGEditorController never registers its own handler.
//
// DISPOSAL (Opus M3):
//   Widget dispose() calls disposeAsync() then dispose() on the controller.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:vanguard_media_engine/vanguard_media_engine.dart';

// ──────────────────────────────────────────────────────────────────────────────
// MethodChannel — same shared channel as all Phase 7 dev_ routes.
// This widget OWNS the handler registration; controller delegates from here.
// ──────────────────────────────────────────────────────────────────────────────

const _channel = MethodChannel('vanguard_media_engine');

// ──────────────────────────────────────────────────────────────────────────────
// VanguardEditorControllerPlayground
// ──────────────────────────────────────────────────────────────────────────────

/// Phase 7 Stage 7.7: Editor Controller API proof playground.
///
/// Uses [VGEditorController] with [VGEditorDraft] to drive all lifecycle steps
/// through the formal typed API rather than raw method channel calls.
class VanguardEditorControllerPlayground extends StatefulWidget {
  const VanguardEditorControllerPlayground({super.key});

  @override
  State<VanguardEditorControllerPlayground> createState() =>
      _VanguardEditorControllerPlaygroundState();
}

class _VanguardEditorControllerPlaygroundState
    extends State<VanguardEditorControllerPlayground> {
  // ── Draft baseline ─────────────────────────────────────────────────────────
  //
  // Stage 7.7 uses two 5-second clips with trim windows matching 7.6 baseline.
  // clipA: 5s full window → trimStartSeconds=0.0, trimEndSeconds=5.0
  // clipB: 5s full window → trimStartSeconds=0.0, trimEndSeconds=5.0
  // Total baseline: 10s.
  //
  // Trim A to 3s: trimStartSeconds=1.0, trimEndSeconds=4.0 → 3s active.
  // Trim B to 3s: trimStartSeconds=1.0, trimEndSeconds=4.0 → 3s active.
  //
  // The native dev_ routes use fixture-generated clip paths, not the
  // sourcePaths in the descriptors. sourcePaths are set to sentinel values
  // that document the fixture intent. (Stage 7.7 limitation.)

  static const _kFixtureSourceA =
      '[dev-fixture] vg_playback_real_clip_A.mp4'; // generated by native
  static const _kFixtureSourceB =
      '[dev-fixture] vg_playback_real_clip_B.mp4'; // generated by native

  static VGClipDescriptor _clipA({bool trimmed = false}) => VGClipDescriptor(
        id: 'clip-A',
        sourcePath: _kFixtureSourceA,
        durationSeconds: 5.0,
        trimStartSeconds: trimmed ? 1.0 : 0.0,
        trimEndSeconds: trimmed ? 4.0 : 5.0,
      );

  static VGClipDescriptor _clipB({bool trimmed = false}) => VGClipDescriptor(
        id: 'clip-B',
        sourcePath: _kFixtureSourceB,
        durationSeconds: 5.0,
        trimStartSeconds: trimmed ? 1.0 : 0.0,
        trimEndSeconds: trimmed ? 4.0 : 5.0,
      );

  static VGEditorDraft _buildDraft({
    bool trimA = false,
    bool trimB = false,
  }) {
    return VGEditorDraft(
      id: 'draft-7.7-proof',
      clips: [_clipA(trimmed: trimA), _clipB(trimmed: trimB)],
      canvasWidth: 640,
      canvasHeight: 360,
      fps: 30,
    );
  }

  // ── Controller ─────────────────────────────────────────────────────────────

  late VGEditorController _controller;

  // ── Trim state (drives draft mutation) ────────────────────────────────────

  bool _trimA = false;
  bool _trimB = false;

  // ── Seek scrub state ──────────────────────────────────────────────────────

  double? _seekDragValue;
  DateTime? _lastScrubSeekAt;

  // ── Export result ─────────────────────────────────────────────────────────

  VGEditorExportResult? _exportResult;

  // ── Lifecycle ─────────────────────────────────────────────────────────────

  @override
  void initState() {
    super.initState();

    _controller = VGEditorController(
      initialDraft: _buildDraft(),
      useRealVideoClips: true,
    );

    // OPUS M1: This widget owns the channel handler.
    // All callbacks are delegated to the controller.
    _channel.setMethodCallHandler(_controller.handleNativeCallback);

    // Initialize after first frame so context is valid.
    WidgetsBinding.instance.addPostFrameCallback((_) => _initialize());
  }

  @override
  void dispose() {
    _channel.setMethodCallHandler(null);
    // OPUS M3: disposeAsync first (fire-and-forget in dispose context),
    // then synchronous dispose.
    _controller.disposeAsync().catchError((_) {});
    _controller.dispose();
    super.dispose();
  }

  // ── Actions ───────────────────────────────────────────────────────────────

  Future<void> _initialize() async {
    try {
      await _controller.initialize();
    } catch (e) {
      // Error is already reflected in controller.value.statusMessage.
    }
  }

  Future<void> _togglePlayPause() async {
    if (_controller.isPlaying) {
      await _controller.pause().catchError((_) {});
    } else {
      await _controller.play().catchError((_) {});
    }
  }

  Future<void> _applyTrim() async {
    final nextDraft = _buildDraft(trimA: _trimA, trimB: _trimB);
    setState(() => _seekDragValue = null);
    try {
      await _controller.updateDraft(nextDraft);
      // Clear prior export result — it no longer matches.
      setState(() => _exportResult = null);
    } catch (e) {
      // Error is already reflected in controller.value.statusMessage.
    }
  }

  Future<void> _export() async {
    try {
      setState(() => _exportResult = null);
      final result = await _controller.export(
        const VGEditorExportRequest(),
      );
      setState(() => _exportResult = result);
    } catch (e) {
      // Error is already reflected in controller.value.statusMessage.
    }
  }

  /// Throttled seek during slider drag — mirrors 7.6 pattern.
  void _throttledScrubSeek(double seconds) {
    final now = DateTime.now();
    if (_lastScrubSeekAt == null ||
        now.difference(_lastScrubSeekAt!) >= const Duration(milliseconds: 80)) {
      _lastScrubSeekAt = now;
      _channel
          .invokeMethod<void>('dev_timelineSeek', {'seconds': seconds})
          .catchError((_) {});
    }
  }

  // ── Build ─────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A0A0F),
      appBar: _buildAppBar(),
      body: ValueListenableBuilder<VGEditorValue>(
        valueListenable: _controller,
        builder: (context, editorValue, _) {
          return _buildBody(editorValue);
        },
      ),
    );
  }

  AppBar _buildAppBar() {
    return AppBar(
      backgroundColor: const Color(0xFF0A0A0F),
      foregroundColor: Colors.white,
      elevation: 0,
      title: const Text(
        'Editor Controller Playground (7.7)',
        style: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
      ),
      actions: [
        Container(
          margin: const EdgeInsets.only(right: 12),
          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
          decoration: BoxDecoration(
            color: const Color(0xFF6C63FF).withValues(alpha: 0.2),
            borderRadius: BorderRadius.circular(8),
            border:
                Border.all(color: const Color(0xFF6C63FF).withValues(alpha: 0.4)),
          ),
          child: const Text(
            'STAGE 7.7',
            style: TextStyle(
              color: Color(0xFF6C63FF),
              fontSize: 11,
              fontWeight: FontWeight.w700,
              letterSpacing: 1.0,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildBody(VGEditorValue editorValue) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // ── Preview ──────────────────────────────────────────────────────
          _buildPreview(editorValue),
          const SizedBox(height: 12),

          // ── Status card ──────────────────────────────────────────────────
          _buildStatusCard(editorValue),
          const SizedBox(height: 12),

          // ── Playback controls ────────────────────────────────────────────
          _buildPlaybackRow(editorValue),
          const SizedBox(height: 12),

          // ── Seek slider ──────────────────────────────────────────────────
          _buildSeekSlider(editorValue),
          const SizedBox(height: 16),

          // ── Draft editor card ────────────────────────────────────────────
          _buildDraftEditorCard(editorValue),
          const SizedBox(height: 12),

          // ── Export card ──────────────────────────────────────────────────
          _buildExportCard(editorValue),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  // ── Preview ───────────────────────────────────────────────────────────────

  Widget _buildPreview(VGEditorValue v) {
    const previewW = 640.0;
    const previewH = 360.0;
    const aspectRatio = previewW / previewH;

    return AspectRatio(
      aspectRatio: aspectRatio,
      child: Container(
        decoration: BoxDecoration(
          color: Colors.black,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: v.isReady
                ? const Color(0xFF6C63FF).withValues(alpha: 0.5)
                : Colors.white12,
          ),
        ),
        clipBehavior: Clip.hardEdge,
        child: v.textureId != null
            ? Texture(textureId: v.textureId!)
            : _buildPreviewPlaceholder(v),
      ),
    );
  }

  Widget _buildPreviewPlaceholder(VGEditorValue v) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          if (v.isReady == false && v.textureId == null)
            const SizedBox(
              width: 32,
              height: 32,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: Color(0xFF6C63FF),
              ),
            )
          else
            const Icon(Icons.videocam_off_outlined,
                color: Colors.white24, size: 40),
          const SizedBox(height: 8),
          Text(
            v.statusMessage ?? 'No preview',
            style: const TextStyle(color: Colors.white38, fontSize: 12),
            textAlign: TextAlign.center,
          ),
        ],
      ),
    );
  }

  // ── Status card ───────────────────────────────────────────────────────────

  Widget _buildStatusCard(VGEditorValue v) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              _Dot(color: v.isReady ? const Color(0xFF00D4AA) : Colors.orange),
              const SizedBox(width: 6),
              Text(
                v.statusMessage ?? (v.isReady ? 'Ready' : 'Not ready'),
                style: const TextStyle(color: Colors.white70, fontSize: 13),
              ),
            ],
          ),
          const SizedBox(height: 6),
          Wrap(
            spacing: 12,
            children: [
              _Label(
                  'Draft',
                  '${v.draft.durationSeconds.toStringAsFixed(1)}s '
                      '(${v.draft.clips.length} clips)'),
              _Label('PTS',
                  '${(v.textureId != null ? v.currentPTS : 0.0).toStringAsFixed(2)}s'),
              _Label('Texture', v.textureId?.toString() ?? '—'),
              _Label('Status',
                  v.isExporting ? 'EXPORTING' : (v.isPlaying ? 'PLAYING' : 'PAUSED')),
            ],
          ),
        ],
      ),
    );
  }

  // ── Playback controls ─────────────────────────────────────────────────────

  Widget _buildPlaybackRow(VGEditorValue v) {
    final canPlay = v.isReady && !v.isExporting;
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        // Play / Pause
        _IconButton(
          id: 'btn_play_pause',
          icon: v.isPlaying ? Icons.pause_rounded : Icons.play_arrow_rounded,
          label: v.isPlaying ? 'Pause' : 'Play',
          enabled: canPlay,
          onTap: _togglePlayPause,
          color: const Color(0xFF6C63FF),
        ),
        const SizedBox(width: 12),
        // Seek to start
        _IconButton(
          id: 'btn_seek_start',
          icon: Icons.skip_previous_rounded,
          label: 'Start',
          enabled: canPlay,
          onTap: () => _controller.seek(0.0).catchError((_) {}),
          color: Colors.white54,
        ),
      ],
    );
  }

  // ── Seek slider ───────────────────────────────────────────────────────────

  Widget _buildSeekSlider(VGEditorValue v) {
    final duration = v.durationSeconds;
    final pts = _seekDragValue ?? v.currentPTS;
    final enabled = v.isReady && duration > 0 && !v.isExporting;

    return Column(
      children: [
        SliderTheme(
          data: SliderThemeData(
            activeTrackColor: const Color(0xFF6C63FF),
            inactiveTrackColor: Colors.white12,
            thumbColor: const Color(0xFF6C63FF),
            overlayColor: const Color(0xFF6C63FF).withValues(alpha: 0.15),
            trackHeight: 3,
            thumbShape:
                const RoundSliderThumbShape(enabledThumbRadius: 7),
          ),
          child: Slider(
            value: pts.clamp(0.0, duration.clamp(0.01, double.infinity)),
            min: 0.0,
            max: duration.clamp(0.01, double.infinity),
            onChanged: enabled
                ? (v) {
                    setState(() => _seekDragValue = v);
                    _throttledScrubSeek(v);
                  }
                : null,
            onChangeEnd: enabled
                ? (v) {
                    setState(() => _seekDragValue = null);
                    _controller.seek(v).catchError((_) {});
                  }
                : null,
          ),
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                _formatPTS(pts),
                style:
                    const TextStyle(color: Colors.white38, fontSize: 11),
              ),
              Text(
                _formatPTS(duration),
                style:
                    const TextStyle(color: Colors.white38, fontSize: 11),
              ),
            ],
          ),
        ),
      ],
    );
  }

  // ── Draft editor card ─────────────────────────────────────────────────────

  Widget _buildDraftEditorCard(VGEditorValue v) {
    final canEdit = v.isReady && !v.isExporting;

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          const Row(
            children: [
              Icon(Icons.edit_outlined,
                  color: Color(0xFF00D4AA), size: 16),
              SizedBox(width: 6),
              Text(
                'Draft Editor',
                style: TextStyle(
                    color: Colors.white70,
                    fontSize: 13,
                    fontWeight: FontWeight.w600),
              ),
            ],
          ),
          const SizedBox(height: 12),

          // Clip A trim toggle
          _TrimRow(
            id: 'trim_clip_a',
            label: 'Clip A',
            trimmed: _trimA,
            baseLabel: '5.0s',
            trimLabel: '3.0s (trim 1–4s)',
            enabled: canEdit,
            onChanged: (v) => setState(() => _trimA = v),
          ),
          const SizedBox(height: 8),

          // Clip B trim toggle
          _TrimRow(
            id: 'trim_clip_b',
            label: 'Clip B',
            trimmed: _trimB,
            baseLabel: '5.0s',
            trimLabel: '3.0s (trim 1–4s)',
            enabled: canEdit,
            onChanged: (v) => setState(() => _trimB = v),
          ),
          const SizedBox(height: 12),

          // Draft duration preview
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: Colors.white.withValues(alpha: 0.04),
              borderRadius: BorderRadius.circular(6),
            ),
            child: Text(
              'Draft duration: '
              '${(_trimA ? 3.0 : 5.0) + (_trimB ? 3.0 : 5.0)} s',
              style: const TextStyle(
                  color: Colors.white54, fontSize: 12),
            ),
          ),
          const SizedBox(height: 12),

          // Apply / Reset buttons
          Row(
            children: [
              Expanded(
                child: _ActionButton(
                  id: 'btn_apply_trim',
                  label: 'Apply Trim',
                  icon: Icons.cut_rounded,
                  enabled: canEdit,
                  color: const Color(0xFF6C63FF),
                  onTap: _applyTrim,
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: _ActionButton(
                  id: 'btn_reset',
                  label: 'Reset',
                  icon: Icons.refresh_rounded,
                  enabled: canEdit,
                  color: Colors.white38,
                  onTap: () {
                    setState(() {
                      _trimA = false;
                      _trimB = false;
                    });
                    _applyTrim();
                  },
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ── Export card ───────────────────────────────────────────────────────────

  Widget _buildExportCard(VGEditorValue v) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: Colors.white10),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          const Row(
            children: [
              Icon(Icons.upload_file_outlined,
                  color: Color(0xFF6C63FF), size: 16),
              SizedBox(width: 6),
              Text(
                'Export',
                style: TextStyle(
                    color: Colors.white70,
                    fontSize: 13,
                    fontWeight: FontWeight.w600),
              ),
            ],
          ),
          const SizedBox(height: 12),

          _ActionButton(
            id: 'btn_export',
            label: v.isExporting ? 'Exporting…' : 'Export Timeline',
            icon: v.isExporting
                ? Icons.hourglass_top_rounded
                : Icons.file_download_outlined,
            enabled: v.isReady && !v.isExporting,
            color: const Color(0xFF00D4AA),
            onTap: _export,
          ),

          if (_exportResult != null) ...[
            const SizedBox(height: 12),
            _ExportResultCard(result: _exportResult!),
          ],
        ],
      ),
    );
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────────────────────────

String _formatPTS(double seconds) {
  final m = (seconds ~/ 60).toString().padLeft(2, '0');
  final s = (seconds % 60).toStringAsFixed(2).padLeft(5, '0');
  return '$m:$s';
}

// ── Small reusable widgets ────────────────────────────────────────────────────

class _Dot extends StatelessWidget {
  const _Dot({required this.color});
  final Color color;

  @override
  Widget build(BuildContext context) => Container(
        width: 8,
        height: 8,
        decoration:
            BoxDecoration(color: color, shape: BoxShape.circle),
      );
}

class _Label extends StatelessWidget {
  const _Label(this.title, this.text);
  final String title;
  final String text;

  @override
  Widget build(BuildContext context) {
    return Text.rich(
      TextSpan(
        children: [
          TextSpan(
            text: '$title: ',
            style: const TextStyle(
                color: Colors.white38, fontSize: 12),
          ),
          TextSpan(
            text: text,
            style: const TextStyle(
                color: Colors.white70,
                fontSize: 12,
                fontWeight: FontWeight.w600),
          ),
        ],
      ),
    );
  }
}

class _IconButton extends StatelessWidget {
  const _IconButton({
    required this.id,
    required this.icon,
    required this.label,
    required this.enabled,
    required this.onTap,
    required this.color,
  });

  final String id;
  final IconData icon;
  final String label;
  final bool enabled;
  final VoidCallback onTap;
  final Color color;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      key: ValueKey(id),
      onTap: enabled ? onTap : null,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
        decoration: BoxDecoration(
          color: enabled
              ? color.withValues(alpha: 0.15)
              : Colors.white.withValues(alpha: 0.04),
          borderRadius: BorderRadius.circular(10),
          border: Border.all(
              color: enabled
                  ? color.withValues(alpha: 0.5)
                  : Colors.white12),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon,
                color: enabled ? color : Colors.white24, size: 20),
            const SizedBox(width: 6),
            Text(
              label,
              style: TextStyle(
                color: enabled ? color : Colors.white24,
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _ActionButton extends StatelessWidget {
  const _ActionButton({
    required this.id,
    required this.label,
    required this.icon,
    required this.enabled,
    required this.color,
    required this.onTap,
  });

  final String id;
  final String label;
  final IconData icon;
  final bool enabled;
  final Color color;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      key: ValueKey(id),
      onTap: enabled ? onTap : null,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 150),
        padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 12),
        decoration: BoxDecoration(
          color: enabled
              ? color.withValues(alpha: 0.12)
              : Colors.white.withValues(alpha: 0.04),
          borderRadius: BorderRadius.circular(8),
          border: Border.all(
              color: enabled
                  ? color.withValues(alpha: 0.4)
                  : Colors.white12),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon,
                size: 16,
                color: enabled ? color : Colors.white24),
            const SizedBox(width: 6),
            Text(
              label,
              style: TextStyle(
                color: enabled ? color : Colors.white24,
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _TrimRow extends StatelessWidget {
  const _TrimRow({
    required this.id,
    required this.label,
    required this.trimmed,
    required this.baseLabel,
    required this.trimLabel,
    required this.enabled,
    required this.onChanged,
  });

  final String id;
  final String label;
  final bool trimmed;
  final String baseLabel;
  final String trimLabel;
  final bool enabled;
  final ValueChanged<bool> onChanged;

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        SizedBox(
          width: 54,
          child: Text(
            label,
            style:
                const TextStyle(color: Colors.white54, fontSize: 12),
          ),
        ),
        Expanded(
          child: Text(
            trimmed ? trimLabel : baseLabel,
            style: TextStyle(
              color: trimmed
                  ? const Color(0xFF00D4AA)
                  : Colors.white38,
              fontSize: 12,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Transform.scale(
          scale: 0.85,
          child: Switch(
            key: ValueKey(id),
            value: trimmed,
            onChanged: enabled ? onChanged : null,
            activeThumbColor: const Color(0xFF00D4AA),
            inactiveThumbColor: Colors.white38,
            inactiveTrackColor: Colors.white12,
          ),
        ),
      ],
    );
  }
}

class _ExportResultCard extends StatelessWidget {
  const _ExportResultCard({required this.result});
  final VGEditorExportResult result;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFF00D4AA).withValues(alpha: 0.06),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(
            color: const Color(0xFF00D4AA).withValues(alpha: 0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            '✓ Export Complete',
            style: TextStyle(
              color: Color(0xFF00D4AA),
              fontSize: 13,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 6),
          _ExportRow('File', result.path.split('/').last),
          _ExportRow(
              'Duration',
              '${result.durationSeconds.toStringAsFixed(2)}s'),
          if (result.width != null && result.height != null)
            _ExportRow('Dimensions', '${result.width}×${result.height}'),
          if (result.fps != null) _ExportRow('FPS', '${result.fps}'),
        ],
      ),
    );
  }
}

class _ExportRow extends StatelessWidget {
  const _ExportRow(this.label, this.text);
  final String label;
  final String text;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(top: 2),
      child: Row(
        children: [
          SizedBox(
            width: 72,
            child: Text(
              '$label:',
              style: const TextStyle(
                  color: Colors.white38, fontSize: 12),
            ),
          ),
          Expanded(
            child: Text(
              text,
              style: const TextStyle(
                color: Colors.white70,
                fontSize: 12,
                fontWeight: FontWeight.w500,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
